### ISSUE TITLE
DNS challenge seems to attempt to alter the wrong zone.

### ISSUE THREAD

**Issue by louwe** [caddy-dns/dynu#1] opened 2024-06-13 02:46 UTC
I have a free subdomain with dynu.com. I've built a Caddy server with this plugin. Caddy version is `v2.8.4 h1:q3pe0wpBj1OcHFZ3n/1nl4V4bxBrYoSoab7rL9BMYNk=` and it is running on a FreeBSD jail 14.0-RELEASE-p6.

Caddyfile:
```
*.louwe.mywire.org {
    tls {
        dns dynu {
            api_token my_token
            own_domain louwe.mywire.org
        }
    }

    @www host www.louwe.mywire.org
    handle @www {
        root * /usr/local/www/blog/public
        encode zstd gzip
        file_server
    }
}
```

Error:
```
{"level":"error","ts":1718243796.2833152,"logger":"tls.obtain","msg":"will retry","error":"[*.louwe.mywire.org] Obtain: [*.louwe.mywire.org] solving challenges: presenting for challenge: adding temporary record for zone \"mywire.org.\": dnsRecord {ID: Type:TXT Name:_acme-challenge.louwe Value:rdVQiapfZvVrc0D7jRLdAmIHYsbBQB4XK3FlBwFuLBA TTL:0s Priority:0 Weight:0}: Post \"https://api.dynu.com/v2/dns/10049633/record\": EOF (order=https://acme-v02.api.letsencrypt.org/acme/order/1398131666/277889062397) (ca=https://acme-v02.api.letsencrypt.org/directory)","attempt":1,"retrying_in":60,"elapsed":1.44899909,"max_duration":2592000}
```
It seems to me that it's attempting to add the TXT temporary record to the wrong zone (mywire.org) instead of (louwe.mywire.org). What am I doing wrong?

For the record, when I do this same DNS challenge flow with acme.sh script, it works flawlessly, but this is sub-optimal as I would like Caddy to manage that instead for more fool-proof integration.

**Comment by taviowong** [comment] 2024-06-14 06:09
The zone is set by Caddy and should not be a problem because I have obtained certs successfully for my Dynu subdomain.

It seems the problem is caused by an EOF response from the Dynu API. Can you let it retry for a while and see if it is just a transient error?

**Comment by ItsIgnacioPortal** [comment] 2024-06-20 23:45
@louwe 
I've found that this works for me, using the now deprecated lego package:
1. Install xcaddy: https://github.com/caddyserver/xcaddy/releases
2. Compile caddy `v2.7.6`. We have to use an older version because the latest versions don't work with `lego-deprecated`. Run: `xcaddy build v2.7.6 --with github.com/caddy-dns/lego-deprecated`
3. Setup your caddyfile:
```caddyfile
	tls {
		dns lego_deprecated dynu
	}
```
4. Setup the environment variable `DYNU_API_KEY` to the API key you get from https://www.dynu.com/en-US/ControlPanel/APICredentials
5. Run caddy: `caddy run`

If you get authentication related errors, you may have to run caddy like this:
```bash
sudo \
DYNU_API_KEY=YOUR_API_KEY_HERE \
caddy run
```

**Comment by louwe** [comment] 2024-06-24 04:09
> The zone is set by Caddy and should not be a problem because I have obtained certs successfully for my Dynu subdomain.

Why would it be set by Caddy? What's the point of the `own_domain` parameter if it's just going to ignore it and use the one given by Caddy? Also, Caddy should be giving it the subdomain rather than the top `mywire.org` domain.
 
> It seems the problem is caused by an EOF response from the Dynu API. Can you let it retry for a while and see if it is just a transient error?

I've just tried it again today and it still gives me the same error so doesn't seem to be transient.

**Comment by taviowong** [comment] 2024-06-24 15:43
> > The zone is set by Caddy and should not be a problem because I have obtained certs successfully for my Dynu subdomain.
> 
> Why would it be set by Caddy? What's the point of the `own_domain` parameter if it's just going to ignore it and use the one given by Caddy? Also, Caddy should be giving it the subdomain rather than the top `mywire.org` domain.

The zone is set by Caddy using DNS lookup for SOA record for the hostname you entered. You can read more about it [in my previous issue](https://github.com/libdns/libdns/issues/123). It is beyond my control to change it so I added a field own_domain to override it internally. There's some conversion behind the scene so whatever is displayed isn't sent to dynu directly; dynu receives your subdomain as input, i.e. louwe.mywire.org, as you expected. So the displayed zone isn't causing the error you are seeing.

> 
> > It seems the problem is caused by an EOF response from the Dynu API. Can you let it retry for a while and see if it is just a transient error?
> 
> I've just tried it again today and it still gives me the same error so doesn't seem to be transient.

I just created a new mywire.org subdomain and got a LetsEncrypt cert using the module so the code should still work... I'm not sure how I can help other than suggesting you let Caddy retry for a while. I do see that the lego dynu module has built-in exponential backoff retry that supposedly handles EOF errors due to the unstable API (https://github.com/go-acme/lego/blob/master/providers/dns/dynu/internal/client.go#L113). I will see if I can add this retry functionality when I have time.

If you have any error messages other than the EOF one, please post them here so I can check if there's any other problem with my code. Thanks!

**Comment by louwe** [comment] 2024-06-29 02:13
@taviowong Is it possible that maybe the use of a wildcard subdomains may have something to do with the failures?

**Comment by taviowong** [comment] 2024-06-30 16:18
> @taviowong Is it possible that maybe the use of a wildcard subdomains may have something to do with the failures?

I am using a wildcard subdomain myself for dynu so it's not related. Would you happen to already have 4 custom DNS records as that's the limit for free accounts?

**Comment by louwe** [comment] 2024-07-05 14:36
I only have 1 record in addition. I did at one point have more, but that also causes acme.sh to fail so it wouldn't be specific just to this plugin.

**Comment by taviowong** [comment] 2024-07-07 09:47
@louwe Can you try again with v0.1.1?

**Comment by jradxl** [comment] 2024-07-10 23:17
Hello,
I've just found the same.
The go test command (from libdns) seems to work fine.
Using within a Caddyfile I get Authorisation errors for the base zone of kozow.com, and not XXX.kozow.com as I would have expected.

I built 2.8.4 today with xcaddy, So wouldn't I have got v0.1.1?
Alas, I'm not a golang programmer
What would I need to do to ensure I have the latest builds.
Thanks

**Comment by louwe** [comment] 2024-07-11 17:22
@taviowong It worked with v0.1.1 and the logs also seem to print the correct domain name.

Thanks for the help!!!

**Comment by taviowong** [comment] 2024-07-12 15:14
> @taviowong It worked with v0.1.1 and the logs also seem to print the correct domain name.
> 
> Thanks for the help!!!
> 
> It looks like these are the changes that made it work?
> 
> ```
> {"level":"info","ts":1720718458.8547428,"msg":"client retrying in 1.466840719s because of Post \"https://api.dynu.com/v2/dns/10049633/record\": EOF"}
> {"level":"info","ts":1720718465.1596737,"msg":"client retrying in 1.330758498s because of Delete \"https://api.dynu.com/v2/dns/10049633/record/10773683\": EOF"}
> ```

Good to hear that it's working for you now ;)
I ported over the retry logic from the lego client so those EOFs returned by Dynu's API won't cause the whole process to fail so easily.

**Comment by taviowong** [comment] 2024-07-12 15:25
> Hello, I've just found the same. The go test command (from libdns) seems to work fine. Using within a Caddyfile I get Authorisation errors for the base zone of kozow.com, and not XXX.kozow.com as I would have expected.
> 
> I built 2.8.4 today with xcaddy, So wouldn't I have got v0.1.1? Alas, I'm not a golang programmer What would I need to do to ensure I have the latest builds. Thanks

Hi there, the problem you are facing looks different from the EOF problem as the go test command works fine as you mentioned (assuming you ran the tests with the environment variables set properly).

To ensure you have the latest builds, your xcaddy build command should have something like `--with github.com/caddy-dns/dynu@v0.1.1` inside.

Have you set the `own_domain` property to your subdomain (i.e. XXX.kozow.com) as that's required for the library to work correctly? If you're still having the problem, please paste the error logs in a new issue for further study. As the original issue has been resolved, I'm closing this issue now.

**Closed by taviowong** 2024-07-12 15:25 UTC
